
# SEO settings
title: "neuro"
title2: "signals" # default: ""
description: "D. W. Zhou"
keywords: ""
url: http://dvwz.github.io # site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/dvwz/dvwz.github.io
disqus_shortname: "davidzhou"
twitter_username: "dvwz"
comments: false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "David Zhou"
  job      : "neuroscience PhD student at MIT"
  bio      : ""
  thumb    : /images/author.jpg
  email    : david.wei.zhou@gmail.com
  url      : http://dvwz.github.io
  github   : http://github.com/dvwz
  twitter  : http://twitter.com/dvwz
  facebook : https://www.facebook.com/dwzhou
  linkedin : http://linkedin.com/in/davidweizhou

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@dvwz"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
